name: Actualizar precios

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          echo "requests" > requirements.txt
          echo "beautifulsoup4" >> requirements.txt
      - run: pip install -r requirements.txt
      - run: python scraper.py
      - name: Mostrar contenido de datos.json
        run: cat datos.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar precios (automático)"
          file_pattern: datos.json
